import { TMovie } from "../types";

export const movieData: TMovie[] = [
    {
        adult: false,
        backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
        genre_ids: [34],
        id: 569094,
        original_language: "en",
        original_title: "Spider-Man: Across the Spider-Verse",
        overview:
            "Майлз Моралес отправляется в приключение по мультивселенной вместе с Гвен Стейси и новой командой Людей-пауков, которым предстоит столкнуться с могущественным злодеем.",
        popularity: 892.875,
        poster_path: "/7fNjczb3059gNOzyoeYAWoDmYPr.jpg",
        release_date: "2023-05-31",
        title: "Человек-паук: Паутина вселенных",
        video: false,
        vote_average: 8.4,
        vote_count: 2652,
    },
    {
        adult: false,
        backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
        genre_ids: [34],
        id: 569094,
        original_language: "en",
        original_title: "Spider-Man: Across the Spider-Verse",
        overview:
            "Майлз Моралес отправляется в приключение по мультивселенной вместе с Гвен Стейси и новой командой Людей-пауков, которым предстоит столкнуться с могущественным злодеем.",
        popularity: 892.875,
        poster_path: "/7fNjczb3059gNOzyoeYAWoDmYPr.jpg",
        release_date: "2023-05-31",
        title: "Человек-паук: Паутина вселенных",
        video: false,
        vote_average: 8.4,
        vote_count: 2652,
    },
    {
        adult: false,
        backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
        genre_ids: [34],
        id: 569094,
        original_language: "en",
        original_title: "Spider-Man: Across the Spider-Verse",
        overview:
            "Майлз Моралес отправляется в приключение по мультивселенной вместе с Гвен Стейси и новой командой Людей-пауков, которым предстоит столкнуться с могущественным злодеем.",
        popularity: 892.875,
        poster_path: "/7fNjczb3059gNOzyoeYAWoDmYPr.jpg",
        release_date: "2023-05-31",
        title: "Человек-паук: Паутина вселенных",
        video: false,
        vote_average: 8.4,
        vote_count: 2652,
    },
    {
        adult: false,
        backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
        genre_ids: [34],
        id: 569094,
        original_language: "en",
        original_title: "Spider-Man: Across the Spider-Verse",
        overview:
            "Майлз Моралес отправляется в приключение по мультивселенной вместе с Гвен Стейси и новой командой Людей-пауков, которым предстоит столкнуться с могущественным злодеем.",
        popularity: 892.875,
        poster_path: "/7fNjczb3059gNOzyoeYAWoDmYPr.jpg",
        release_date: "2023-05-31",
        title: "Человек-паук: Паутина вселенных",
        video: false,
        vote_average: 8.4,
        vote_count: 2652,
    },
];
